# Enterprise Web Template Application Configuration

app:
  environment: local  # local/dev/prod
  jwt:
    secret: ${JWT_SECRET:bXktc2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtb25seS1jaGFuZ2UtaW4tcHJvZHVjdGlvbi1lbnRlcnByaXNlLXdlYi10ZW1wbGF0ZQ==}
    expiration: 86400000  # 24 hours in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds
  cors:
    allowed-origins: 
      - "http://localhost:3000"
      - "http://localhost:3001"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
      - "OPTIONS"
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
    max-file-size: 10MB
    max-request-size: 50MB
    max-size: ${FILE_MAX_SIZE:10485760} # 10MB in bytes
    allowed-types: ${FILE_ALLOWED_TYPES:image/jpeg,image/png,image/gif,image/webp}
    profile-image-dir: ${PROFILE_IMAGE_DIR:profile-images}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/enterprise_web_template?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update  # create-drop for dev, validate for prod
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  # Security configuration
  security:
    oauth2:
      client:
        registration: {}
  
  # WebSocket configuration
  websocket:
    message-size-limit: 8192
    send-buffer-size-limit: 512000
    
  # Actuator configuration
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
    endpoint:
      health:
        show-details: when-authorized

# Logging configuration
logging:
  level:
    com.enterprise.webtemplate: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/application.log

# Server configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
    multipart:
      max-file-size: ${app.file.max-file-size}
      max-request-size: ${app.file.max-request-size}

---
# Local Development Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: INFO
    com.enterprise.webtemplate: DEBUG

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: INFO
    com.enterprise.webtemplate: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

logging:
  level:
    root: INFO
    com.enterprise.webtemplate: INFO